// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://ifwcgzdznxphmmcsuufq.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlmd2NnemR6bnhwaG1tY3N1dWZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNTM0MDgsImV4cCI6MjA2NjgyOTQwOH0.whFPRVdI2cEFaRXcjxecA65Ux3DXTfMcM3iMuw-KbbE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});